services:
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodstore_app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
